In [13]:
import pandas as pd

In [16]:
print(df)

                      Review Sentiments
0  The product is excellenct   Positive
1          Very poor quality   Negative
2        I love this product   Positive
3         Woest product ever   Negative

In [17]:
df.head()

                      Review Sentiments
0  The product is excellenct   Positive
1          Very poor quality   Negative
2        I love this product   Positive
3         Woest product ever   Negative

In [18]:
print(df.columns)

Index(['Review', 'Sentiments'], dtype='object')

In [19]:
print(df.shape)

(4, 2)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Review      4 non-null      object
 1   Sentiments  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [21]:
df.describe()

                           Review Sentiments
count                           4          4
unique                          4          2
top     The product is excellenct   Positive
freq                            1          2

In [22]:
df.isnull().sum()

Review        0
Sentiments    0
dtype: int64

In [23]:
df.dtypes

Review        object
Sentiments    object
dtype: object

In [24]:
print("Dataset loaded successfully!")
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Dataset loaded successfully!
Rows: 4
Columns: 2